stories-portal/config/routes.rb
Rails.application.routes.draw do


# ESSA ROTA DO MANAGE TEM QUE SER A PRIMEIRA
# Rotas que atendem ao ambiente BACKOFFICE
  namespace :manage do
    root to: 'home#index'
    resources :newsletters, only: [:index]
    resources :products do
      collection do
        post :gallery_change
        get 'cart_floating'
      end
    end
    resources :customers
    resources :categories
    resources :orders, only: [:index, :show]
  end

 ## Rotas que atendem ao ambiente PAINEL DO USUÁRIO
    namespace :panel do
      root to: 'my_orders#index'
      resources :my_orders, only: [:index, :show]
      resources :addresses do
        collection do
          get :xhr_update
        end
      end
      resources :my_personal_details, only: [:index, :show, :edit]
      patch 'my_personal_details/customer', to: 'my_personal_details#customer'

    end

# Rota RAIZ
  root to: 'home#index'
  match '/shipping', via: :get, to: 'application#shipping', as: :shipping  
  
# Rotas que atendem ao DEVISE
  devise_for :customers, :path => '/', :path_names => {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
## Rotas que atendem ao PRODUCTS

  resources :products, controller: :shops, only: [:index]
  resources :products, only: [:show] do
    collection do
      get :xhr_mail_shipping
    end
  end
## Rotas que atendem ao SHOPS
  resources :shops do
    collection do
      get 'cart_floating'
    end
  end

## Rotas que atendem ao CHECKOUT
resources :newsletters, only: [:create]
get '/checkout', to: 'checkout#index', as: :checkout
get '/success', to: 'checkout#order_success', as: :success
patch '/checkout/customer', to: 'checkout#customer'
get '/checkout/buy', to: 'checkout#buy'

## Rotas que atendem ao CARRINHO
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  get '/carts/postal_code', to: 'carts#postal_code'
  get 'carts/show'
  
end

stories-portal/app/controllers/panel/addresses_controller.rb
class Panel::AddressesController < Panel::BaseController 
  before_action :set_address, only: [:edit, :update, :destroy, :xhr_update]
  before_action :set_addresses, only: [:index, :create, :xhr_update]
  def index
    @address = Address.new
  end
  def edit
  end
  def destroy
    if @address.destroy
      if @address.postal_code == cookies[:cep]
        cookies.delete :cep
      end
      redirect_to panel_addresses_path
    end
  end
  def xhr_update
    if !params[:main_address].blank? && !params[:id].blank?
      @address.update({main_address: params[:main_address]})
      redirect_to panel_addresses_path
    end
  end
  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to panel_addresses_path
    else
      render :index
    end
  end

  private
  def set_addresses
    @addresses = Address.where(customer_id: current_customer.id).order(main_address: :desc, updated_at: :desc).page(params[:page]).per(3)    
  end
  def set_address
    @address = Address.find params[:id]
  end
  def address_params
    params.require(:address).permit(:alias, :main_address, :postal_code, :number, :type_address, :street, :complement, :reference, :neighborhood, :city, :state_id, :customer_id)
  end
end

stories-portal/app/controllers/panel/base_controller.rb
class Panel::BaseController < ApplicationController
  before_action :authenticate_customer!
end

stories-portal/app/controllers/panel/my_orders_controller.rb
class Panel::MyOrdersController < Panel::BaseController 
  def index
    @orders = Order.where(customer_id: current_user).order(updated_at: :desc).page(params[:page]).per(5)
  end
end

stories-portal/app/controllers/panel/my_personal_details_controller.rb
class Panel::MyPersonalDetailsController < Panel::BaseController
  def index
    @customer = current_customer
  end
  def customer
    if current_customer.update(customer_params)
      redirect_to panel_my_personal_details_path    
    end
  end
  protected
  def update_resource(resource, params)
    resource.update_without_password(customer_params)
  end  

  private
  def customer_params
  	params.require(:customer).permit(:name, :lastname, :username, :cpf, :password, :password_confirmation, :current_password)
  end  
end

stories-portal/app/helpers/panel/addresses_helper.rb
module Panel::AddressesHelper
end

stories-portal/app/helpers/panel/my_orders_helper.rb
module Panel::MyOrdersHelper
end

stories-portal/app/helpers/panel/my_personal_details_helper.rb
module Panel::MyPersonalDetailsHelper
end

stories-portal/app/helpers/panel_helper.rb
module PanelHelper
end

stories-portal/app/views/panel/my_personal_details/index.html.erb
<%= render partial: "/layouts/partials/top_background_randon", locals: {name: 'Painel do Cliente'} %>

<div class='oxy-section'>
   <div class='oxy-section__content'>
<%=form_for @customer, as: :customer , url: panel_my_personal_details_customer_path, method: :patch do |f| %>

      <div class="mdl-grid mdl-grid--no-fullwidth">
         <div class="mdl-cell mdl-cell--3-col mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-cell--2-order-tablet mdl-cell--2-order-phone">
            <div class="mdl-card mdl-shadow--2dp oxy-widget">
               <div class="mdl-card__title oxy-widget__title mdl-card--border">
                  <i class="material-icons">&#xE853;</i>
                  <h3 class=mdl-card__title-text>Meus Dados</h3>
               </div>
               <div class="mdl-card__supporting-text oxy-widget__content">
                  <%=render 'panel/partials/links'%>
               </div>
            </div>
         </div>

        <div class="mdl-grid mdl-cell mdl-cell--9-col mdl-cell--6-col-tablet mdl-cell--4-col-phone oxy-margin-bottom-40">
        <div class="mdl-shadow--2dp oxy-card-order" id="error-explanation">
        
        </div>
                <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-tablet mdl-cell-4-col-phone">
                    <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
                        <%=f.label :email, class: 'mdl-textfield__label'%>
                        <%=f.text_field :email, class: 'mdl-textfield__input', disabled: true%>
                    </div>
                </div>
        
                <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell-4-col-phone">
                    <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
                        <%=f.label :name, class: 'mdl-textfield__label'%>
                        <%=f.text_field :name, class: 'mdl-textfield__input' %>
                    </div>
                </div>
                <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell-4-col-phone">
                    <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
                        <%=f.label :lastname, class: 'mdl-textfield__label' %>
                        <%=f.text_field :lastname, class: 'mdl-textfield__input' %>
                    </div>
                </div>
                <div class="mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet mdl-cell-4-col-phone">
                    <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
                        <%=f.label :cpf, class: 'mdl-textfield__label' %>
                        <%=f.text_field :cpf, class: 'mdl-textfield__input maskcpf' %>
                    </div>
                </div>
                <div class="mdl-cell mdl-cell--6-col mdl-cell--8-col-tablet mdl-cell-4-col-phone">
                    <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
                        <%=f.label :username, class: 'mdl-textfield__label' %>
                        <%=f.text_field :username, class: 'mdl-textfield__input' %>
                    </div>
                </div>
                <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-tablet mdl-cell-4-col-phone">
                    <%= f.submit 'Alterar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored", id:'submit_customer'%>
                </div>
            </div>
         </div>
            <%end%>
      </div>
   </div>