stories-portal/config/routes.rb
Rails.application.routes.draw do


# ESSA ROTA DO MANAGE TEM QUE SER A PRIMEIRA
# Rotas que atendem ao ambiente BACKOFFICE
  namespace :manage do
    root to: 'home#index'
    resources :newsletters, only: [:index]
    resources :products do
      collection do
        post :gallery_change
        get 'cart_floating'
      end
    end
    resources :customers
    resources :categories
    resources :orders, only: [:index, :show]
  end

 ## Rotas que atendem ao ambiente PAINEL DO USUÁRIO
    namespace :panel do
      root to: 'my_orders#index'
      resources :my_orders, only: [:index, :show]
      resources :addresses do
        collection do
          get :xhr_update
        end
      end
      resources :my_personal_details, only: [:index, :show, :edit]
      patch 'my_personal_details/customer', to: 'my_personal_details#customer'

    end

# Rota RAIZ
  root to: 'home#index'
  match '/shipping', via: :get, to: 'application#shipping', as: :shipping  
  
# Rotas que atendem ao DEVISE
  devise_for :customers, :path => '/', :path_names => {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
## Rotas que atendem ao PRODUCTS

  resources :products, controller: :shops, only: [:index]
  resources :products, only: [:show] do
    collection do
      get :xhr_mail_shipping
    end
  end
## Rotas que atendem ao SHOPS
  resources :shops do
    collection do
      get 'cart_floating'
    end
  end

## Rotas que atendem ao CHECKOUT
resources :newsletters, only: [:create]
get '/checkout', to: 'checkout#index', as: :checkout
get '/success', to: 'checkout#order_success', as: :success
patch '/checkout/customer', to: 'checkout#customer'
get '/checkout/buy', to: 'checkout#buy'

## Rotas que atendem ao CARRINHO
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  get '/carts/postal_code', to: 'carts#postal_code'
  get 'carts/show'
  
end

stories-portal/app/controllers/panel/addresses_controller.rb
class Panel::AddressesController < Panel::BaseController 
  before_action :set_address, only: [:edit, :update, :destroy, :xhr_update]
  before_action :set_addresses, only: [:index, :create, :xhr_update]
  def index
    @address = Address.new
  end
  def edit
  end
  def destroy
    if @address.destroy
      if @address.postal_code == cookies[:cep]
        cookies.delete :cep
      end
      redirect_to panel_addresses_path
    end
  end
  def xhr_update
    if !params[:main_address].blank? && !params[:id].blank?
      @address.update({main_address: params[:main_address]})
      redirect_to panel_addresses_path
    end
  end
  def create
    @address = Address.new(address_params)
    if @address.save
      redirect_to panel_addresses_path
    else
      render :index
    end
  end

  private
  def set_addresses
    @addresses = Address.where(customer_id: current_customer.id).order(main_address: :desc, updated_at: :desc).page(params[:page]).per(3)    
  end
  def set_address
    @address = Address.find params[:id]
  end
  def address_params
    params.require(:address).permit(:alias, :main_address, :postal_code, :number, :type_address, :street, :complement, :reference, :neighborhood, :city, :state_id, :customer_id)
  end
end

stories-portal/app/controllers/panel/base_controller.rb
class Panel::BaseController < ApplicationController
  before_action :authenticate_customer!
end

stories-portal/app/controllers/panel/my_orders_controller.rb
class Panel::MyOrdersController < Panel::BaseController 
  def index
    @orders = Order.where(customer_id: current_user).order(updated_at: :desc).page(params[:page]).per(5)
  end
end

stories-portal/app/controllers/panel/my_personal_details_controller.rb
class Panel::MyPersonalDetailsController < Panel::BaseController
  def index
    @customer = current_customer
  end
  def customer
    if current_customer.update(customer_params)
      redirect_to panel_my_personal_details_path    
    end
  end
  protected
  def update_resource(resource, params)
    resource.update_without_password(customer_params)
  end  

  private
  def customer_params
  	params.require(:customer).permit(:name, :lastname, :username, :cpf, :password, :password_confirmation, :current_password)
  end  
end

stories-portal/app/helpers/panel/addresses_helper.rb
module Panel::AddressesHelper
end

stories-portal/app/helpers/panel/my_orders_helper.rb
module Panel::MyOrdersHelper
end

stories-portal/app/helpers/panel/my_personal_details_helper.rb
module Panel::MyPersonalDetailsHelper
end

stories-portal/app/helpers/panel_helper.rb
module PanelHelper
end

stories-portal/app/views/panel/addresses/_form.html.erb
    <div class="mdl-cell mdl-cell--3-col mdl-cell--2-col-tablet mdl-cell-4-col-phone">
        <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
            <%=f.label :postal_code, class: 'mdl-textfield__label' %>
            <%=f.text_field :postal_code, class: 'mdl-textfield__input shipping add_address' %>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--9-col mdl-cell--2-col-tablet mdl-cell-4-col-phone">
        <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
            <%=f.label :alias, class: 'mdl-textfield__label'%>
            <%=f.text_field :alias, class: 'mdl-textfield__input' %>
        </div>
    </div>    
    <div class="mdl-cell mdl-cell--8-col mdl-cell--6-col-tablet mdl-cell-4-col-phone">
        <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
            <%=f.label :street, class: 'mdl-textfield__label'%>
            <%=f.text_field :street, class: 'mdl-textfield__input street_address' %>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--4-col mdl-cell--2-col-tablet mdl-cell-4-col-phone">
        <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
            <%=f.label :number, class: 'mdl-textfield__label' %>
            <%=f.text_field :number, class: 'mdl-textfield__input' %>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell-4-col-phone">
        <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
            <%=f.label :complement, class: 'mdl-textfield__label'%>
            <%=f.text_field :complement, class: 'mdl-textfield__input'%>
        </div>
    </div>

    <div class="mdl-cell mdl-cell--6-col mdl-cell--3-col-tablet mdl-cell-4-col-phone">
        <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
            <%=f.label :neighborhood, class: 'mdl-textfield__label' %>
            <%=f.text_field :neighborhood, class: 'mdl-textfield__input neighborhood_address' %>
        </div>
    </div>
    <div class="mdl-cell mdl-cell--6-col mdl-cell--3-col-tablet mdl-cell-4-col-phone">
        <div class="mdl-textfield mdl-textfield--full-width mdl-textfield--floating-label mdl-js-textfield">
            <%=f.label :city, class: 'mdl-textfield__label'%>
            <%=f.text_field :city, class: 'mdl-textfield__input city_address'%>
        </div>
    </div>
    <div class="mdl-grid" id="align-center">
        <div class="mdl-cell mdl-cell--12-col mdl-cell--4-col-tablet mdl-cell-4-col-phone" id="align-center">
            <%=f.collection_select :state_id, State.all, :id, :full_name, {prompt: 'Selecione um Estado'}, class: 'state_address'%>

        </div>
    </div>
    <% if controller_name != "checkout"%>
    <div class="mdl-cell mdl-cell--12-col mdl-cell--12-col-tablet mdl-cell-12-col-phone">
      <%=f.label :main_address, class: 'mdl-radio mdl-js-radio mdl-js-ripple-effect' do %>
          <%=f.check_box :main_address, class: 'mdl-radio__button'%>
          <span class="mdl-radio__label"><%= f.label :main_address %></span>
      <%end%>
    </div>
    <%end%>

stories-portal/app/views/panel/addresses/_index.html.erb
<% @addresses.each do |address| %>
    <tr class="<%=(address.main_address ? 'mdl-cell--success' : '')%>">
        <td>
          <%if !address.main_address%>
            <%= link_to xhr_update_panel_addresses_path(main_address: !address.main_address, id: address.id), {remote: true} do%>
              <i class="material-icons">&#xE888;</i>
            <%end%>
          <%else%>
              <i class="material-icons">&#xE876;</i>
          <%end%>
        </td>
        <td><%= address.alias %></td>
        <td><%= address.street %></td>
        <td><%= address.number %></td>
        <td><%= address.neighborhood %></td>
        <td><%= address.city %></td>
        <td>
            <%=link_to panel_address_path(id: address.id), method: :delete, class: 'mdl-button mdl-js-button mdl-button--accent mdl-button--icon' do %>
              <i class="material-icons">delete_sweep</i>
            <%end%>
        </td>
    </tr>                    
<% end %>

stories-portal/app/views/panel/addresses/index.html.erb
<%= render partial: "/layouts/partials/top_background_randon", locals: {name: 'Painel do Cliente'} %>

<div class=oxy-section>
   <div class=oxy-section__content>
   
      <div class="mdl-grid mdl-grid--no-fullwidth">
         <div class="mdl-cell mdl-cell--3-col mdl-cell--8-col-tablet mdl-cell--4-col-phone mdl-cell--2-order-tablet mdl-cell--2-order-phone">
            <div class="mdl-card mdl-shadow--2dp oxy-widget">
               <div class="mdl-card__title oxy-widget__title mdl-card--border">
                  <i class="material-icons">&#xE88A;</i>
                  <h3 class=mdl-card__title-text>Meus Endereços</h3>
               </div>
               <div class="mdl-card__supporting-text oxy-widget__content">
                  <%=render 'panel/partials/links'%>
               </div>
            </div>
         </div>         
         
         <div class="mdl-grid mdl-cell mdl-cell--top mdl-cell--9-col mdl-cell--8-col-tablet mdl-cell--4-col-phone oxy-margin-top-10">

            <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp oxy-full-width oxy-data-table oxy-data-table--center oxy-data-table--middle">
                <%if !@addresses.blank?%>
                <thead>
                    <tr>
                      <th>Endereço Principal</th>
                      <th>Apelido</th>
                      <th>Logradouro</th>
                      <th>Número</th>
                      <th>Bairro</th>
                      <th>Cidade</th>
                      <th>Ação</th>
                    </tr>
                </thead>
                <tbody id="table_addresses">
                <% @addresses.each do |address| %>
                    <tr class="<%=(address.main_address ? 'mdl-cell--success' : '')%>">
                        <td>
                          <%if !address.main_address%>
                            <%= link_to xhr_update_panel_addresses_path(main_address: !address.main_address, id: address.id), {remote: true} do%>
                            <i class="material-icons">&#xE888;</i>
                            <%end%>
                          <%else%>
                              <i class="material-icons">&#xE876;</i>
                          <%end%>
                        </td>
                        <td><%= address.alias %></td>
                        <td><%= address.street %></td>
                        <td><%= address.number %></td>
                        <td><%= address.neighborhood %></td>
                        <td><%= address.city %></td>
                        <td>
                          <%=form_tag "/panel/addresses/#{address.id}",  method: :delete do %>
                            <%= button_tag "Delete", class: 'mdl-button mdl-js-button mdl-button--accent mdl-button--icon', data: {disable_with: '<i class="material-icons">delete_sweep</i>'.html_safe} do%>
                              <i class="material-icons">delete_sweep</i>
                            <%end%> 
                          <%end%>
                        </td>
                    </tr>                    
                <% end %>
                </tbody>
            <%else%>
                <tbody>
                    <tr>
                        <td>Não há endereços cadastrados</td>
                    </tr>
                </tbody>
            <%end%>
            </table>
            <%= paginate @addresses %>           
    <%=form_for([:panel, @address]) do |f|%>
        <%=f.hidden_field :customer_id, value: current_customer.id%>
                      
            <div class="mdl-grid mdl-cell mdl-cell--12-col mdl-cell--8-col-tablet mdl-cell--4-col-phone oxy-margin-bottom-40 mdl-shadow--2dp oxy-full-width oxy-margin-top-10">
                <%= render partial: "layouts/partials/with_messages_of_errors", locals: {object: @address} %>
                <div class="mdl-grid oxy-margin-bottom-10">    
                    <%=render partial: 'panel/addresses/form', locals: {f: f}%>
                    
                    <div class="mdl-grid mdl-cell mdl-cell--12-col mdl-cell--4-col-tablet mdl-cell-4-col-phone centralize_button">
                        <%= f.submit 'Adicionar Endereço', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored centralize_button" %>
                    </div>
                </div>
            </div>
        <%end%>

         </div>
      </div>
   </div>
</div>

stories-portal/app/views/panel/addresses/index.js.erb
$("#table_addresses").html("<%= j render partial: 'index' %>");