stories-portal/config/routes.rb
Rails.application.routes.draw do


# ESSA ROTA DO MANAGE TEM QUE SER A PRIMEIRA
# Rotas que atendem ao ambiente BACKOFFICE
  namespace :manage do
    root to: 'home#index'
    resources :newsletters, only: [:index]
    resources :products do
      collection do
        post :gallery_change
        get 'cart_floating'
      end
    end
    resources :customers
    resources :categories
    resources :orders, only: [:index, :show]
  end

 ## Rotas que atendem ao ambiente PAINEL DO USUÁRIO
    namespace :panel do
      root to: 'my_orders#index'
      resources :my_orders, only: [:index, :show]
      resources :addresses do
        collection do
          get :xhr_update
        end
      end
      resources :my_personal_details, only: [:index, :show, :edit]
      patch 'my_personal_details/customer', to: 'my_personal_details#customer'

    end

# Rota RAIZ
  root to: 'home#index'
  match '/shipping', via: :get, to: 'application#shipping', as: :shipping  
  
# Rotas que atendem ao DEVISE
  devise_for :customers, :path => '/', :path_names => {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
## Rotas que atendem ao PRODUCTS

  resources :products, controller: :shops, only: [:index]
  resources :products, only: [:show] do
    collection do
      get :xhr_mail_shipping
    end
  end
## Rotas que atendem ao SHOPS
  resources :shops do
    collection do
      get 'cart_floating'
    end
  end

## Rotas que atendem ao CHECKOUT
resources :newsletters, only: [:create]
get '/checkout', to: 'checkout#index', as: :checkout
get '/success', to: 'checkout#order_success', as: :success
patch '/checkout/customer', to: 'checkout#customer'
get '/checkout/buy', to: 'checkout#buy'

## Rotas que atendem ao CARRINHO
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  get '/carts/postal_code', to: 'carts#postal_code'
  get 'carts/show'
  
end

stories-portal/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user, access)
    @user = user
    @access = access
    set_admin_permissions
  end
    def set_admin_permissions
      return unless access.admin?
      can :manage, :all if access.admin?
    end
end

stories-portal/app/models/access.rb
class Access < ApplicationRecord
  has_one :customer
  
  ADMIN = Access.find_by_name('ADMIN')
  MANAGER = Access.find_by_name('MANAGER')
  CUSTOMER = Access.find_by_name('CUSTOMER')

  cattr_accessor :admin do
    [
      ADMIN, MANAGER
    ]
  end

  def admin?
    admin.include?(self)
  end

  def customer?
    self == CUSTOMER
  end

  def manager?
    self == MANAGER
  end
end

stories-portal/app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  has_many :orders
  belongs_to :state
  validates :alias, :street, :number, :postal_code, :neighborhood, presence: true
  after_save :main
  after_destroy :verify_main, :set_main
  
  def main
    if self.main_address
      self.class.where(customer: self.customer).where.not(id: self.id).update_all(main_address: false)
    else
      if self.class.where(customer: self.customer).count == 1
        self.class.where(id: self.id).update({main_address: true})   
      end     
    end
  end
  def set_main
    if self.class.where(main_address: true, customer: self.customer).blank? && self.class.where(main_address: false, customer: self.customer).count > 1
      self.class.where(customer: self.customer).first.update({main_address: true})
    end
  end
  def verify_main
    if self.class.where(customer: self.customer).count == 1
      self.class.where(customer: self.customer).update({main_address: true})
    end         
  end
end

stories-portal/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

	def create_slug
    self.slug = self.name.parameterize
  end	

	def	capitalized
		self.name = self.name.split(' ').map(&:capitalize).join(' ')
	end

end

stories-portal/app/models/category.rb
class Category < ApplicationRecord
	before_save :create_slug, :capitalized

	has_and_belongs_to_many :products, join_table: :categories_has_products, uniq: true, dependent: :destroy
	validates :name, presence: true, uniqueness: true
	scope :searchable, ->(conditions){where("name LIKE ?", "%#{conditions}%")}
	def to_param
    slug
  end
	def create_slug
    super
  end	

	def	capitalized
		super
	end

	def destroy
		if !products.present?
			super
		end
	end
end

stories-portal/app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :access
  has_many :addresses
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  scope :searchable, -> (conditions){where("name like ? OR email like ?", conditions, conditions)}
  before_save :access_default

  accepts_nested_attributes_for :addresses
  
  def access_default
    if self.access.blank?
      self.access = Access.find_by_name('CUSTOMER')
    end
  end
  private 
end

stories-portal/app/models/gallery.rb
class Gallery < ApplicationRecord
	belongs_to :attachable, :polymorphic => true
	has_attached_file :media,
		:styles => {
			thumb: '60x',
			small: '450x',
			large: '900x'
		}
  validates_attachment_size :media, :less_than => 20.megabytes
  validates_attachment_content_type :media, :content_type => ["image/jpeg", "image/jpg", "image/png", "image/gif"]
		
end

stories-portal/app/models/newsletter.rb
class Newsletter < ApplicationRecord
  validates :email, uniqueness: true
  before_save :active
  
  def active
    self.active = true
  end
end

stories-portal/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :payment
  belongs_to :customer
  belongs_to :order_status
  has_many :order_items
  belongs_to :address
  before_create :set_order_status
  before_save :update_sub_total, :set_total
  def sub_total
    order_items.collect{|item| item.valid? ? (item.quantity * item.unit_price) : 0}.sum
  end

  def final_total
    sub_total + self.shipping.to_s.to_d
  end

  private
  def set_total
    self.total = final_total
  end
  def set_order_status
    self.order_status_id = 1
  end
  
  def update_sub_total
    self[:subtotal] = sub_total
  end
end

stories-portal/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present
  validates :product_id, presence: true
  
  before_save :finalize
  
  def unit_price
    if persisted?
      self[:unit_price]
    else
      (product.promotional_price.zero? ? product.sale_price : product.promotional_price)
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.blank?
      errors.add(:product, "is not valid or is not active")
    end
  end
  def order_present
    if order.blank?
      errors.add(:order, "is not valid")
    end
  end
  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

stories-portal/app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

stories-portal/app/models/payment.rb
class Payment < ApplicationRecord
	has_many :orders
end

stories-portal/app/models/product.rb
class Product < ApplicationRecord
	before_save :create_slug, :capitalized

	has_and_belongs_to_many :categories, join_table: :categories_has_products, uniq: true, dependent: :destroy
	has_many :order_items

	has_many :pictures, class_name: Gallery, as: :attachable, dependent: :destroy
	
	validates :name, :sku, :description_short, :sale_price, :weight, :height, :width, :depth, :qty_min_in_cart, :qty_max_in_cart, presence: true
	validates :qty_min_in_cart, numericality: {only_integer: true, greater_than: 0}
	validates :sku, uniqueness: true	
	validates :categories, presence: true
	
	default_scope {where(active: true)}

	def to_param
    slug
  end

	def create_slug
    super
  end	
	
	def	capitalized
		super
	end

  def next
    self.class.where("id > ?", id).first
  end

  def prev
    self.class.where("id < ?", id).last
  end	
end

stories-portal/app/models/state.rb
class State < ApplicationRecord
  has_many :addresses

  def full_name
    "#{self.unit}"
  end
end

stories-portal/app/helpers/carts_helper.rb
module CartsHelper
end

stories-portal/app/helpers/checkout_helper.rb
module CheckoutHelper
end

stories-portal/app/helpers/home_helper.rb
module HomeHelper
end

stories-portal/app/helpers/panel_helper.rb
module PanelHelper
end

stories-portal/app/helpers/products_helper.rb
module ProductsHelper

end

stories-portal/app/helpers/shop_helper.rb
module ShopHelper
end

stories-portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <meta charset=utf-8>
      <meta http-equiv=X-UA-Compatible content="IE=edge">
      <meta name=description content>
      <meta name=viewport content="width=device-width, initial-scale=1">
      <title>Feira dos Cosméticos</title>
      <!-- Favicons-->
      <link rel="icon" href="<%=image_url('favicon.ico')%>" sizes="32x32">      
      <link rel=apple-touch-icon href="<%=image_url('apple-touch-icon.png')%>">
      <link href="https://fonts.googleapis.com/css?family=Roboto:400,100,300,300italic,400italic,500,500italic,700,900" rel=stylesheet type=text/css>
      <link rel=stylesheet href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <body class="front_<%=controller_name%> <%= action_name %>">

    <div class="mdl-layout mdl-js-layout mdl-layout--overlay-drawer-button mdl-layout--fixed-header">
      <%= render "layouts/partials/header" %>
      <main class=mdl-layout__content> 
        <%= yield %>
        <%= render "layouts/partials/footer" %>
      </main>
    </div>
    <%= render "/layouts/partials/cart_floating" unless ['carts'].include?(controller_name)%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
  </body>
</html>

stories-portal/app/views/layouts/partials/_carousel.html.erb
<div class=oxy-section>
   <div class=oxy-section__content>
      <div class="rev_slider_wrapper fullwidthbanner-container">
         <div id=homepage-slider class=rev_slider data-version=5.0>
            <ul>
               <li data-title="Slide 1" data-index=slide-1 data-thumb="<%=image_url('slide-full-maquiagem-1.jpg')%>">
                  <img src="<%=image_url('slide-full-maquiagem-1.jpg')%>" alt="Slide 1" data-bgposition="center top" data-kenburns=on data-duration=7000 data-scalestart=100 data-scaleend=110 data-offsetstart="-50 100" data-offsetend="100 -150" data-bgfit=105 data-bgfitend=100 data-bgpositionend="center bottom">
                  <div class="tp-caption tp-resizeme mdl-typography--display-3 mdl-typography--font-thin" data-x=left data-hoffset=500 data-y=top data-voffset=250 data-transform_in=o:0;e:Power4.easeIn; data-transform_idle=o:1;s:1000; data-transform_out=o:0;s:500;e:Power4.easeOut; data-start=1000>Feira dos Cosméticos</div>
                  <div class="tp-caption tp-resizeme" data-x=left data-y=top data-hoffset=500 data-voffset=335 data-start=1500 data-transform_in=o:0;e:Power1.easeIn; data-transform_idle=o:1;s:500; data-transform_out=o:0;s:500;e:Power4.easeOut; style="height: 1px; width: 200px;background: #000;"></div>
                  <div class="tp-caption tp-resizeme mdl-typography--title mdl-typography--font-light" data-x=left data-y=top data-hoffset=500 data-voffset=360 data-start=2000 data-transform_in=o:0;e:Power4.easeIn; data-transform_idle=o:1;s:600; data-transform_out=o:0;s:600;e:Power1.easeOut;>
                     <p style="font-size: 21px; line-height: 1.5">NOVIDADES todos os dias. Aproveite!<br>Sâo mais de 1000 produtos para você escolher.<br><strong>Frete Grátis</strong> em mais de 50 produtos.<br></p>
                  </div>
                  <div class="tp-caption tp-resizeme tp-caption-mdl-button mdl-button mdl-button--raised mdl-button--colored" data-x=left data-y=top data-hoffset=500 data-voffset=480 data-start=3000 data-transform_in=o:0;y:100; data-transform_idle=x:0;o:1;s:600; data-transform_out=o:0;s:800;e:Power1.easeOut;><a href="<%=url_for(shops_path)%>" style="color: #fff;">Catálogo</a></div>
               </li>
               <li data-title="Slide 2" data-index=slide-2 data-thumb="<%=image_url('carrousel_model_1.jpg')%>">
                  <img src="<%=image_url('carrousel_model_1.jpg')%>" alt="slide2" data-bgposition="left top" data-kenburns=on data-duration=7000 data-scalestart='100' data-scaleend='115' data-offsetstart="250 100" data-offsetend="-150 -50" data-ease="Linear.easeNone" data-bgfit='110' data-bgfitend='100' data-bgpositionend="left bottom">
                  <div class="tp-caption tp-resizeme mdl-typography--display-3 mdl-typography--font-thin oxy-color-light" data-x=left data-y=top data-hoffset=720 data-voffset=250 data-start=1000 data-transform_in=o:0; data-transform_idle=o:1;s:1000; data-transform_out=o:0;s:600;>VERÃO 2016</div>
                  <div class="tp-caption tp-resizeme" data-x=left data-y=top data-hoffset=720 data-voffset=335 data-start=1000 data-transform_in=o:0; data-transform_idle=o:1;s:800; data-transform_out=o:0;s:600; style="height: 1px; width: 100px;background: #fff;"></div>
                  <div class="tp-caption tp-resizeme mdl-typography--title mdl-typography--font-light oxy-color-light" data-x=left data-y=top data-voffset=360 data-hoffset=720 data-start=2000 data-transform_in=o:0; data-transform_idle=o:1;s:800; data-transform_out=o:0;s:600;>
                     <p style="font-size: 21px; line-height: 1.5">Arrase neste verão<br>com uma pele bem cuidada.<br>Conheça nossos lançamentos.<br></p>
                  </div>
                  <div class="tp-caption tp-resizeme tp-caption-mdl-button mdl-button mdl-button--raised mdl-button--accent" data-x=left data-y=top data-hoffset=720 data-voffset=480 data-start=3000 data-transform_in=o:0;y:100; data-transform_idle=x:0;o:1;s:600; data-transform_out=o:0;s:600;><a href="<%=url_for(shops_path)%>" style="color: #fff;">Produtos</a></div>
               </li>
               <li data-title="Slide 3" data-index=slide-3 data-thumb="<%=image_url('carrousel_model_product.jpg')%>">
                  <img src="<%=image_url('carrousel_model_product.jpg')%>" alt="Slide 3" data-bgposition="left center" data-kenburns=on data-duration=7000 data-scalestart=100 data-scaleend=115 data-offsetstart="-150 -200" data-offsetend="350 -450" data-ease=Linear.easeNone data-bgfit=110 data-bgfitend=100 data-bgpositionend="left center">
                  <div class="tp-caption tp-resizeme mdl-typography--display-3 mdl-typography--font-thin" data-x=left data-y=top data-hoffset=550 data-voffset=250 data-start=1000 data-transform_in=o:0; data-transform_idle=o:1;s:1000; data-transform_out=o:0;s:600;>OFERTA LOUCA!</div>
                  <div class="tp-caption tp-resizeme" data-x=left data-y=top data-hoffset=550 data-voffset=335 data-start=1500 data-transform_in=o:0; data-transform_idle=o:1;s:800; data-transform_out=o:0;s:600; style="height: 1px; width: 200px;background: #000;"></div>
                  <div class="tp-caption tp-resizeme mdl-typography--title mdl-typography--font-light" data-x=left data-y=top data-hoffset=550 data-voffset=360 data-start=2000 data-transform_in=o:0; data-transform_idle=o:1;s:800; data-transform_out=o:0;s:600;>
                     <p style="font-size: 21px; line-height: 1.5">Aproveite nossa queima de estoque e se <br>proteja neste verão.<br> Diversas marcas de Protetores Solares<br> Escolha já o seu!<br></p>
                  </div>
                  <div class="tp-caption tp-resizeme tp-caption-mdl-button mdl-button mdl-button--raised mdl-button--colored" data-x=left data-y=top data-hoffset=550 data-voffset=515 data-start=3000 data-transform_in=o:0;y:100; data-transform_idle=x:0;o:1;s:600; data-transform_out=o:0;s:600;><a href="<%=url_for(shops_path)%>" style="color: #fff;">Ofertas</a></div>
               </li>
            </ul>
         </div>
      </div>
   </div>
</div>

stories-portal/app/views/layouts/partials/_cart_floating.html.erb
<%# CART FLOATING %>
<button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--fab mdl-button--colored oxy-button-fab oxy-js-button-shopping-cart mdl-badge oxy-button-fab__badge" data-badge="<%=current_order.order_items.size%>"><i class=material-icons>shopping_cart</i></button>
      <div class="mdl-layout__drawer mdl-layout__drawer--right oxy-product-cart" id="cart-floating">
         <span class=mdl-layout-title>Carrinho</span>
         <div class=oxy-layout__divider></div>
         <div class=oxy-product-cart__body>
            <ul class="oxy-list" id="cart_floating">
              <% if !current_order.order_items.blank?%>
                <%current_order.order_items.each do |item|%>
                <li class=oxy-list__item>
                    <a href="<%=product_path(id: item.product.slug)%>" class="oxy-list__icon">
                      <img src="<%=image_url(item.product.pictures.first.media.url(:thumb))%>" alt="<%=item.product.name%>">
                    </a>
                    <div class="oxy-list__item-text">
                      <a href="<%=product_path(id: item.product.slug)%>" class="oxy-list__title"><%=item.product.name%></a> 
                      <span class="oxy-list__subtitle"><%=item.quantity%> x <%=number_to_currency item.unit_price%></span>
                    </div>
                    <div class=oxy-list__item-secondary-action>
                      <%= link_to order_item_path(id: item.id), data: { confirm: "Você tem certeza que deseja remover o produto '#{item.product.name}' da sua compra?" }, method: :delete, class: 'mdl-button mdl-js-button mdl-button--accent mdl-button--icon' do%>
                        <i class="material-icons">delete_sweep</i>
                      <%end%>
                    </div>
                </li>
                <%end%>
              <%end%>
            </ul>
            <div class=oxy-product-cart__actions>
               <div class=oxy-layout__divider></div>
               <h3 class=oxy-product-cart__total>Subtotal: <%=number_to_currency current_order.subtotal%></h3>
               <div class=oxy-layout__divider></div>
               <div class=mdl-grid>
                  <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell--2-col-phone"><a href="<%=cart_path%>" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent oxy-full-width">Carrinho</a></div>

                  <% if !current_order.order_items.blank? && controller_name != 'checkout'%>
                  <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell--2-col-phone"><a href="<%=checkout_path%>" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary oxy-full-width">Concluir</a></div>
                  <% end %>
               </div>
            </div>
         </div>
      </div>
  <div id="side-cart-obfuscator" class="mdl-layout__obfuscator"></div>

stories-portal/app/views/layouts/partials/_featured_products.html.erb
<% # PRODUTO PATROCINADO EM DESTAQUE %>

<div class="oxy-section">
  <div class="oxy-section__content">
    <div class="mdl-grid mdl-grid--no-fullwidth">
      <div class="mdl-cell mdl-cell--12-col">
        <h2 class="mdl-typography--display-1 mdl-typography--text-center mdl-typography--font-light oxy-margin-top-40 oxy-margin-bottom-20 oxy-animation" data-os-animation=fadeIn data-os-animation-delay=0.1s>Produtos em destaques</h2>
        <div class="oxy-divider oxy-divider--center oxy-animation" data-os-animation=fadeIn data-os-animation-delay=0.1s>
          <div class="oxy-divider__border"></div>
        </div>
      </div>
    </div>
  <% if !@featured_products.blank? %>
    <div class=mdl-grid>
      <%@featured_products.each do |product|%>
        <div class="mdl-cell mdl-cell--2-col mdl-cell--2-col-tablet mdl-cell--2-col-phone oxy-animation" data-os-animation="fadeIn" data-os-animation-delay="0.1s">
          <div class="mdl-card mdl-shadow--2dp oxy-card-product">
            <div class="mdl-card__media oxy-card-product__media">
              <a href="<%=url_for(product_path(product.slug))%>">
                <img alt="some product" class=oxy-card-product__image src="<%=product.pictures.first.media.url(:small)if !product.pictures.blank?%>"> 
                <img alt="<%=product.name%>" class=oxy-card-product__image src="<%=product.pictures.first.media.url(:small) if !product.pictures.blank?%>">
              </a>
              <div class="mdl-card__title oxy-card-product__title">
                <h3 class="mdl-card__title-text oxy-card-product__title-text">
                  <a href="<%=product_path(product.slug)%>" class="mdl-typography--font-light">
                    <%=product.name%>
                  </a>
                </h3>
                <span class="mdl-typography--text-uppercase mdl-typography--font-bold oxy-card-product__tags">
                  <%product.categories.each do |category|%>
                    <a href="<%=shop_path(id: category.slug)%>" rel="tag">
                      <%=truncate(category.name, length: 20)%>
                    </a>
                  <%end%>
                </span>
              </div>
              <%if !product.promotional_price.zero?%><div class="oxy-card-product__badge oxy-product-badge">Oferta</div><%end%>
            </div>
            <div class="mdl-card__actions oxy-card-product-actions">
              <strong class="mdl-typography--headline oxy-product-price mdl-featured-products">
                <%if !product.promotional_price.zero?%>
                  <del><span><%=number_to_currency(product.sale_price) -%></span></del>
                  <ins><span><%=number_to_currency(product.promotional_price) -%></span></ins>
                <%else%>
                  <ins><span><%=number_to_currency(product.sale_price)%></span></ins>
                <%end%>
              </strong> 
              <%=form_for OrderItem.new, {remote: true, method: :post, authenticity_token: true} do |f|%>
                  <%= f.hidden_field :quantity, value: 1%>
                  <%= f.hidden_field :product_id, value: product.id %>
                  <%=f.button class: 'oxy-button-add-product oxy-js-button-add-product mdl-button mdl-js-button mdl-button--icon mdl-button--raised mdl-button--colored mdl-js-ripple-effect' do %>
                  <i class='material-icons'>add_shopping_cart</i>
                  <!--<button type="submit" class="oxy-button-add-product oxy-js-button-add-product mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" data-product="<%=product.id%>">
                  </button>-->
                  <%end%>
              <%end%>
            </div>
          </div>
        </div>
      
      <%end%>
    </div>
  <%end%>

  </div>
</div>

stories-portal/app/views/layouts/partials/_header.html.erb
<header class="mdl-layout__header mdl-layout__header--waterfall oxy-layout__header oxy-layout__header--transparent">
   <div class=mdl-layout__header-row>
      <a class=mdl-layout-title href="<%=url_for(root_path)%>"><img src="<%=image_url('logo.png')%>" alt=BeSmart></a>
      <div class=mdl-layout-spacer></div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable mdl-textfield--floating-label mdl-textfield--align-right">
         <label class="mdl-button mdl-js-button mdl-button--icon" for="search"><i class=material-icons>search</i></label>
         <div class=mdl-textfield__expandable-holder>
         <%=form_tag shops_path, method: :get do %>
          <%#<input class=mdl-textfield__input type=text name=sample id=waterfall-exp>%>
          <%=text_field_tag :search, nil, class: 'mdl-textfield__input' %>
         <%end%>
         </div>
      </div>
   </div>
   <div class="mdl-layout__header-row oxy-margin-top--10">
      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link  mdl-nav-link mdl-typography--text-center " href="<%=url_for(shops_path)%>">
          <i class="material-icons header-icon">&#xE8C9;</i><i class="header-icon-text">&nbsp;Categorias</i></a>
        <a class="mdl-navigation__link mdl-nav-link mdl-typography--text-center " href="<%=url_for(products_path)%>">
          <i class="material-icons header-icon">&#xE8EF;</i><i class="header-icon-text">&nbsp;Produtos</i></a>
        <%if customer_signed_in?%>
          <a class="mdl-navigation__link mdl-nav-link mdl-typography--text-center " href="<%=panel_root_path%>">
            <i class="material-icons header-icon">&#xE871;</i><i class="header-icon-text">&nbsp;Meu Painel</i></a>
        <%else%>
          <a class="mdl-navigation__link mdl-nav-link mdl-typography--text-center " href="<%=url_for(new_customer_session_path)%>">
            <i class="material-icons header-icon">&#xE871;</i><i class="header-icon-text">&nbsp;Entrar/Cadastrar-se</i></a>
        <%end%>
      </nav>
   </div>
</header>

<%= render 'layouts/partials/nav' %>

stories-portal/app/views/layouts/partials/_nav.html.erb
<div class=mdl-layout__drawer>
  <a class="mdl-layout-title" href="<%=url_for(root_path)%>">
    <img src="<%=image_url('logo-dark.png')%>" alt="<%=APPLICATION_NAME%>">
  </a>
  <nav class=mdl-navigation>
    <a class=mdl-navigation__link href="<%=url_for(root_path)%>">
      <i class="material-icons mdl-navigation__icon">home</i> Página Inicial</a> 

    <span class=mdl-navigation__link-divider></span> 
    
    <a class=mdl-navigation__link href="<%=url_for(shops_path)%>">
      <i class="material-icons mdl-navigation__icon">shopping_basket</i> Produtos</a> 

    <a class="mdl-navigation__link mdl-navigation__link--submenu" href=#>
      <i class="material-icons mdl-navigation__icon">bookmark</i> Categorias</a>
      <nav class="mdl-navigation mdl-navigation__submenu">
        <%if !@categories.blank?%>
        <%@categories.each do |category|%>
         <a class="mdl-navigation__link mdl-navigation__submenu__link" href="/shops/<%=category.slug%>"><%=category.name%></a>
        <%end%>
        <%end%>
      </nav>


      <a class=mdl-navigation__link href="/cart">
        <i class="material-icons mdl-navigation__icon">shopping_cart</i> Carrinho</a> 
    <span class=mdl-navigation__link-divider></span> 
    

    <% if customer_signed_in?%>
    <a class="mdl-navigation__link mdl-navigation__link--submenu" href="javascript:void(0)">
      <i class="material-icons mdl-navigation__icon">account_box</i> Painel do Usuário</a>
    <nav class="mdl-navigation mdl-navigation__submenu">
      <a class="mdl-navigation__link mdl-navigation__submenu__link" href="<%=panel_my_personal_details_path%>">Alterar Dados</a>
      <a class="mdl-navigation__link mdl-navigation__submenu__link" href="<%=panel_addresses_path%>">Meus Endereços</a> 
      <a class="mdl-navigation__link mdl-navigation__submenu__link" href="<%=panel_my_orders_path%>">Meus Pedidos</a> 
      <%= link_to destroy_customer_session_path, method: :delete, class:"mdl-navigation__link mdl-navigation__submenu__link" do %>
      Sair
      <%end%>
     </nav>    
    <%else%>        
      <a class="mdl-navigation__link" href="<%=url_for(new_customer_session_path)%>">
        <i class="material-icons mdl-navigation__icon">account_box</i> Entrar/Cadastrar-se</a>
    <%end%>

  </nav>
</div>