stories-portal/config/routes.rb
Rails.application.routes.draw do


# ESSA ROTA DO MANAGE TEM QUE SER A PRIMEIRA
# Rotas que atendem ao ambiente BACKOFFICE
  namespace :manage do
    root to: 'home#index'
    resources :newsletters, only: [:index]
    resources :products do
      collection do
        post :gallery_change
        get 'cart_floating'
      end
    end
    resources :customers
    resources :categories
    resources :orders, only: [:index, :show]
  end

 ## Rotas que atendem ao ambiente PAINEL DO USUÁRIO
    namespace :panel do
      root to: 'my_orders#index'
      resources :my_orders, only: [:index, :show]
      resources :addresses do
        collection do
          get :xhr_update
        end
      end
      resources :my_personal_details, only: [:index, :show, :edit]
      patch 'my_personal_details/customer', to: 'my_personal_details#customer'

    end

# Rota RAIZ
  root to: 'home#index'
  match '/shipping', via: :get, to: 'application#shipping', as: :shipping  
  
# Rotas que atendem ao DEVISE
  devise_for :customers, :path => '/', :path_names => {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
## Rotas que atendem ao PRODUCTS

  resources :products, controller: :shops, only: [:index]
  resources :products, only: [:show] do
    collection do
      get :xhr_mail_shipping
    end
  end
## Rotas que atendem ao SHOPS
  resources :shops do
    collection do
      get 'cart_floating'
    end
  end

## Rotas que atendem ao CHECKOUT
resources :newsletters, only: [:create]
get '/checkout', to: 'checkout#index', as: :checkout
get '/success', to: 'checkout#order_success', as: :success
patch '/checkout/customer', to: 'checkout#customer'
get '/checkout/buy', to: 'checkout#buy'

## Rotas que atendem ao CARRINHO
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  get '/carts/postal_code', to: 'carts#postal_code'
  get 'carts/show'
  
end

stories-portal/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}
  validate :product_present
  validate :order_present
  validates :product_id, presence: true
  
  before_save :finalize
  
  def unit_price
    if persisted?
      self[:unit_price]
    else
      (product.promotional_price.zero? ? product.sale_price : product.promotional_price)
    end
  end

  def total_price
    unit_price * quantity
  end

  private
  def product_present
    if product.blank?
      errors.add(:product, "is not valid or is not active")
    end
  end
  def order_present
    if order.blank?
      errors.add(:order, "is not valid")
    end
  end
  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

stories-portal/app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    if @order.order_items.where(product_id: params[:order_item][:product_id]).blank?
      @order_item = @order.order_items.new(order_item_params)
      if @order.save
        session[:order_id] = @order.id
      end
    else
      order_item = @order.order_items.where(product_id: params[:order_item][:product_id]).last
      quantity = order_item.quantity + params[:order_item][:quantity].to_i
      if order_item.update_attributes({quantity: quantity})
        @order_items = @order.order_items
        @order.save
      end
    end
    respond_to do |format|
      format.html { redirect_to cart_path }
      format.js   {render controller: :shops}
      format.json { render :show, status: :created }
    end
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    if @order_item.update_attributes(order_item_params)
      @order_items = @order.order_items
      @order.save
    end
    redirect_to cart_path
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])    
    @order_item.destroy
    @order_items = @order.order_items
    if @order_items.blank?
      session[:order_id] = nil
      @order.destroy
    end
    redirect_to cart_path
  end

  private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

stories-portal/app/helpers/order_items_helper.rb
module OrderItemsHelper
end

stories-portal/app/views/order_items/_create.html.erb
<%# CART FLOATING %>

<button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--fab mdl-button--colored oxy-button-fab oxy-js-button-shopping-cart mdl-badge oxy-button-fab__badge" data-badge="<%=@order.order_items.size%>"><i class=material-icons>shopping_cart</i></button>
      <div class="mdl-layout__drawer mdl-layout__drawer--right oxy-product-cart">
         <span class=mdl-layout-title>Carrinho</span>
         <div class=oxy-layout__divider></div>
         <div class=oxy-product-cart__body>
            <ul class=oxy-list>
              <% if !@order.order_items.blank?%>
                <%@order.order_items.each do |item|%>
                <li class=oxy-list__item>
                    <a href="<%=product_path(id: item.product.slug)%>" class="oxy-list__icon">
                      <img src="<%=image_url(item.product.pictures.first.media.url(:thumb))%>" alt="<%=item.product.name%>">
                    </a>
                    <div class="oxy-list__item-text">
                      <a href="<%=product_path(id: item.product.slug)%>" class="oxy-list__title"><%=item.product.name%></a> 
                      <span class="oxy-list__subtitle"><%=item.quantity%> x <%=number_to_currency item.unit_price%></span>
                    </div>
                    <div class=oxy-list__item-secondary-action>
                      <%= link_to order_items_path(id: item.id), data: { confirm: "Você tem certeza que deseja remover o produto '#{item.product.name}' da sua compra?" }, method: :delete, class: 'mdl-button mdl-js-button mdl-button--accent mdl-button--icon' do%>
                        <i class="material-icons">delete_sweep</i>
                      <%end%>
                    </div>
                </li>
                <%end%>
              <%end%>
            </ul>
            <div class=oxy-product-cart__actions>
               <div class=oxy-layout__divider></div>
               <h3 class=oxy-product-cart__total>Subtotal: <%=number_to_currency @order.subtotal%></h3>
               <div class=oxy-layout__divider></div>
               <div class=mdl-grid>
                  <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell--2-col-phone"><a href="<%=cart_path%>" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent oxy-full-width">Carrinho</a></div>

                  <% if !@order.order_items.blank?%>
                  <div class="mdl-cell mdl-cell--6-col mdl-cell--4-col-tablet mdl-cell--2-col-phone"><a href="<%=checkout_path%>" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary oxy-full-width">Concluir</a></div>
                  <% end %>
               </div>
            </div>
         </div>
      </div>
  <div id="side-cart-obfuscator" class="mdl-layout__obfuscator"></div>

stories-portal/app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

stories-portal/app/views/order_items/create.js.erb
$('html body').html("<%=render j 'create'%>")

stories-portal/app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

stories-portal/app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>